### ISSUE TITLE
Result doesn't match with example   

### ISSUE THREAD

**Issue by TishinIlia** [amberlowe1001/amber-HtML#2]
@amberlowe1001 Hi Amber!
Please, check again, your result in index.html doesn't look like https://drive.google.com/file/d/1RKx3za-SPeNUJXkEsejkpj45-mqUFzWR/view?usp=sharing and index2.html  doesn't look like https://drive.google.com/file/d/1h2r57_PcH6yjWnt4_wWrGE6DYY9_c2ip/view

BtW:
1

<div class="container">

<body>

is semantic error

2  <nav class="nav"> hasn't closing tag
       
3 
                                    <div class ="ground-beef">
                                        <li> (1) pound ground lean (7% fat) beef</li>
                                    </div>
                                    is absolutely wrong construction

https://github.com/amberlowe1001/amber-HtML/blob/2ab36aefa57053fd74c160d47fb4463b96f3623c/hw/index.html#L10

**Comment by amberlowe1001** [comment]
what do you mean? what is wrong with it? I used the template page. I just styled it. I wasn't supposed to do that? There weren't any actual directions in the file. I checked the read me too. I just found the template and the HTML file and put them together.

**Comment by amberlowe1001** [comment]
I wish that you would of explained your comment so that I could fix it or understand what you are referring to. Saying it is "absolutely wrong" doesn't give me any feedback that I can use,

**Comment by TishinIlia** [comment]
@amberlowe1001 a little bit hard to write comments here because github transforms all tags to HTML. I will send you all comments in slack soon
